import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// Plays the short confirmation tone that tells the user a code was read.
///
/// The tone is a bundled asset instead of a system sound: `SystemSound.play`
/// maps to the platform's UI click effect, which Android silences whenever the
/// user turns off touch sounds — that is, the confirmation would be missing on
/// most phones, which is exactly the problem this abstraction exists to fix.
abstract interface class ScanTonePlayer {
  /// Builds the platform player ahead of the first read.
  ///
  /// Without it the first tone paid for player creation, audio context, player
  /// mode and asset loading — several platform round trips — while the person
  /// was already waiting for a result. Failing here is not an error: [play]
  /// falls back on its own.
  Future<void> warmUp();
  Future<void> play();
  Future<void> dispose();
}

/// The production tone player, backed by the bundled WAV asset.
class AssetScanTonePlayer implements ScanTonePlayer {
  AssetScanTonePlayer({AudioPlayer Function()? playerFactory})
      : _playerFactory = playerFactory ?? AudioPlayer.new;

  /// Generated by `tool/generate_scan_beep.py` and shipped inside the package.
  static const String assetPath = 'sounds/scan_success.wav';

  final AudioPlayer Function() _playerFactory;
  AudioPlayer? _player;
  Future<AudioPlayer>? _preparation;

  /// The player is built on the first tone, not on construction: a screen that
  /// never reads a code — or a platform without an audio plugin — should not
  /// create a platform player just by being opened.
  Future<AudioPlayer> _prepare() async {
    final AudioPlayer player = _playerFactory();
    _player = player;
    // `mixWithOthers` keeps music or a call from being interrupted by a beep
    // that lasts a tenth of a second.
    await player.setAudioContext(
      AudioContextConfig(focus: AudioContextConfigFocus.mixWithOthers).build(),
    );
    await player.setPlayerMode(PlayerMode.lowLatency);
    await player.setReleaseMode(ReleaseMode.stop);
    await player.setSource(AssetSource(assetPath));
    return player;
  }

  @override
  Future<void> warmUp() async {
    await (_preparation ??= _prepare());
  }

  @override
  Future<void> play() async {
    final Future<AudioPlayer> preparation = _preparation ??= _prepare();
    final AudioPlayer player = await preparation;
    // Rewind first: a second scan arriving while the tone is still playing
    // would otherwise be silent.
    await player.seek(Duration.zero);
    await player.resume();
  }

  @override
  Future<void> dispose() async => _player?.dispose();
}

/// Confirmation for a successful read: sound and vibration, each one honouring
/// its own setting.
///
/// Neither channel is allowed to break a scan. If the audio plugin is missing
/// or fails — an unsupported platform, a device without an audio route — the
/// class degrades to the system click sound and stops trying.
class ScanFeedback {
  ScanFeedback({ScanTonePlayer? tonePlayer}) : _tonePlayer = tonePlayer ?? AssetScanTonePlayer();

  final ScanTonePlayer _tonePlayer;
  bool _toneUnavailable = false;

  @visibleForTesting
  bool get toneUnavailable => _toneUnavailable;

  /// Prepares the tone player before the first read.
  ///
  /// Safe to call more than once and safe to ignore: a platform without an
  /// audio plugin simply leaves the player unavailable.
  Future<void> warmUp() async {
    if (_toneUnavailable) return;
    try {
      await _tonePlayer.warmUp();
    } on Object {
      _toneUnavailable = true;
    }
  }

  Future<void> success({required bool sound, required bool vibration}) async {
    if (vibration) {
      try {
        // Heavy, not medium: this is the confirmation that a code was read,
        // and on a phone held at arm's length a soft tick goes unnoticed.
        await HapticFeedback.heavyImpact();
      } on Object {
        // A device without a vibrator must not interrupt the reading.
      }
    }
    if (sound) await _playTone();
  }

  Future<void> _playTone() async {
    if (!_toneUnavailable) {
      try {
        await _tonePlayer.play();
        return;
      } on Object {
        _toneUnavailable = true;
      }
    }
    try {
      await SystemSound.play(SystemSoundType.click);
    } on Object {
      // Nothing else to fall back to.
    }
  }

  Future<void> dispose() async {
    try {
      await _tonePlayer.dispose();
    } on Object {
      // The player may never have been created on this platform.
    }
  }
}
